### ISSUE TITLE
Code does not compile when using web10g

### ISSUE THREAD

**Issue by skostuch** [ndt-project/ndt#183]
After merging changes from websocket branch, code does not compile when using web10g (it works only for web100). It seems like blocks of code unique for web10g does still use old variable names and also generate some warnings that due to -Werror flag being set result in compilation error too.

**Comment by aaronmbr** [comment]
I fixed some web10g compilation issues in master, are these the ones that you were hitting?

**Comment by skostuch** [comment]
Among the others yes. I've committed changes that also fix compilation warnings which I was getting and which due to -Werror flag resulted in compilation error. Now code should compile fine both on web10g and web100 (tested on both). If changes look good for you then feel free to close this issue.

**Comment by aaronmbr** [comment]
Apparently, 4.6 uses a "-Wunused-but-set-variable" by default which will cause all the code of the form:

 int ret = pipe(mon_pipe);

to spit out an error as well. It might make more sense to convert the 'system' ones to:

if (system("echo 1 > /proc/sys/net/ipv4/route/flush") != 0) {
     // spit out a warning
}

The pipes all seem to be packet trace things, so you could probably do a similar:

if (pipe(mon_pipe) != 0) {
     // spit out a warning
}
else {
    // the rest of the packet trace code
}

If nothing else, I think if the pipe doesn't work, the rest of the code may unhelpfully segfault. You may want to do a similar error check for the fork() itself.

**Comment by skostuch** [comment]
I've committed changes with proper fixes

**Comment by aaronmbr** [comment]
Seems good. Closing.
